# Generated by Django 3.2.8 on 2021-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortenedUrl', models.CharField(max_length=256, verbose_name='shortenedUrl')),
                ('urlToShorten', models.CharField(max_length=256, verbose_name='urlToShorten')),
                ('views', models.IntegerField(verbose_name='views')),
                ('rand_id', models.IntegerField(db_index=True, verbose_name='rand_id')),
            ],
        ),
    ]
